### PR TITLE
:recycle: Simplified isCurrentUrl

### PR DESCRIPTION
**Pull request by mariush2**
Solves [AB#546933](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/546933)

### CODE REVIEW

**Review by Brynjulf — COMMENTED** [review]
Has this been tested in an application? like pwex, because I am not able to navigate using the sidebar with this change. I don't know what I have done wrong

**Comment by mariush2** [comment]
Pushed a new commit now @Brynjulf , tested in PWEX

**Review by Brynjulf — APPROVED** [review]
Looks good!

**Review by aslakihle — APPROVED** [review]
👌

**Pull request merged**
